#include<stdio.h>

int main(void)
{
    char flag[29];
    printf("input: ");
    scanf("%s", flag);
    if(flag[0]=='2'){
        if(flag[1]=='0'){
            if(flag[2]=='2'){
                if(flag[3]=='2'){
                    if(flag[4]=='_'){
                        if(flag[5]=='K'){
                            if(flag[6]=='C'){
                                if(flag[7]=='T'){
                                    if(flag[8]=='F'){
                                        if(flag[9]=='{'){
                                            if(flag[10]=='t'){
                                                if(flag[11]=='h'){
                                                    if(flag[12]=='i'){
                                                        if(flag[13]=='s'){
                                                            if(flag[14]=='_'){
                                                                if(flag[15]=='i'){
                                                                    if(flag[16]=='s'){
                                                                        if(flag[17]=='_'){
                                                                            if(flag[18]=='c'){
                                                                                if(flag[19]=='y'){
                                                                                    if(flag[20]=='b'){
                                                                                        if(flag[21]=='e'){
                                                                                            if(flag[22]=='r'){
                                                                                                if(flag[23]=='_'){
                                                                                                    if(flag[24]=='w'){
                                                                                                        if(flag[25]=='a'){
                                                                                                            if(flag[26]=='r'){
                                                                                                                if(flag[27]=='}'){
                                                                                                                    printf("success\n");
                                                                                                                }
                                                                                                                else{
                                                                                                                    printf("Fail\n");
                                                                                                                }
                                                                                                            }
                                                                                                            else{
                                                                                                                printf("Fail\n");
                                                                                                            }
                                                                                                        }
                                                                                                        else{
                                                                                                            printf("Fail\n");
                                                                                                        }
                                                                                                    }
                                                                                                    else{
                                                                                                        printf("Fail\n");
                                                                                                    }
                                                                                                }
                                                                                                else{
                                                                                                    printf("Fail\n");
                                                                                                }
                                                                                            }
                                                                                            else{
                                                                                                printf("Fail\n");
                                                                                            }
                                                                                        }
                                                                                        else{
                                                                                            printf("Fail\n");
                                                                                        }
                                                                                    }
                                                                                    else{
                                                                                        printf("Fail\n");
                                                                                    }
                                                                                }
                                                                                else{
                                                                                    printf("Fail\n");
                                                                                }
                                                                            }
                                                                            else{
                                                                                printf("Fail\n");
                                                                            }
                                                                        }
                                                                        else{
                                                                            printf("Fail\n");
                                                                        }
                                                                    }
                                                                    else{
                                                                        printf("Fail\n");
                                                                    }
                                                                }
                                                                else{
                                                                    printf("Fail\n");
                                                                }
                                                            }
                                                            else{
                                                                printf("Fail\n");
                                                            }
                                                        }
                                                        else{
                                                            printf("Fail\n");
                                                        }
                                                    }
                                                    else{
                                                        printf("Fail\n");
                                                    }
                                                }
                                                else{
                                                    printf("Fail\n");
                                                }
                                            }
                                            else{
                                                printf("Fail\n");
                                            }
                                        }
                                        else{
                                            printf("Fail\n");
                                        }
                                    }
                                    else{
                                        printf("Fail\n");
                                    }
                                }
                                else{
                                    printf("Fail\n");
                                }
                            }
                            else{
                                printf("Fail\n");
                            }
                        }
                        else{
                            printf("Fail\n");
                        }
                    }
                    else{
                        printf("Fail\n");
                    }
                }
                else{
                    printf("Fail\n");
                }
            }
            else{
                printf("Fail\n");
            }
        }
        else{
            printf("Fail\n");
        }
    }
    else{
        printf("Fail\n");
    }
    return 0;
}